### ISSUE TITLE
R Shiny web tool

### ISSUE THREAD

**Issue by joeflack4** [tfojo1/ending_hiv#1]
## Description
Implement web tool.

## 1.0 Tasks
- [x] 1. Launch boilerplate app
- [x] 2. RunModel page: connect to plot functional interface
- [x] RunModel page: Widgets / dropdown menus to select dimensions / chart options
- [ ] Dynamically generating the arguments
- [ ] Interventions: There's going to be 30 interventions or so eventually. What should we do? Checkbox? Or allow up to 3 interventions. We do want to cache some amount.
- [ ] Connect to the _real_ plot function.
- [ ] Set up file storage.

## 1.0 Deployment
- [ ] QA: Do with the team
- [ ] Deploy to its own website: Look for some domain names. And we'll deploy there later. Should also have its own Shiny account, which Todd owns.

## x.y
_These can be done before or after the 1.0_
- [ ]  Pie in the sky idea: We have a separate tab, and you dynamically run an intervention that you design. We have some number of pre-run interventions. But the user wants to customize their intervention which would take about a minute or two possibly. Then that is cached.
- [ ] Paid service: https://www.shinyapps.io/. Do we need?
