### ISSUE TITLE
To-Do List for Go Live

### ISSUE THREAD

**Issue by tfojo1** [tfojo1/ending_hiv#28]
### Joe
- [x] **1. Put a boilerplate "Coming Soon" for Custom Interventions that we can swap in**
- [x] **2. NEVERMIND on URL**
- [ ] 3. Make it so that changing city does NOT reset selected inputs
- [x] 4. Pop up an error message if no subgroups are selected in a category within demographic subgroups
- [x] 5. Make it so that if you are loading a preset, the plot automatically renders

### Todd

- [x] **1. Fill in the FAQ in the Help Section**
- [x] **2. Fill in the About Section**
- [x] **3. Change 'Epidemiological Target' to "Observed Data" in the figure Legend**
- [x] **4. Change 'Prep Coverage' to "Prep Uptake**
- [x] **5. Upload data files for remaining 28 MSAs**
- [x] 6. Expand tip for custom vs prespecified interventions
- [ ] 7. Add legend for figure detailing interventions
- [ ] 8. Reposition/resize figure labels
- [ ] 9. Start plotting interventions at present day
- [x] 10. Expand the top tip box (more detail)

### Unassigned
- [ ] 1. **Dynamic figure size plot size**: Can we change it without re-rendering. To do this, it might need to use JS, not R; maybe. Slider bar: 5 levels; small to large. Image size selector. What we're sure we can do is change the size pre-render. But if we can do it post render, that'd be great.
